// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/type_tss.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	gitlab_com_thorchain_thornode_common "gitlab.com/thorchain/thornode/common"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TssVoter struct {
	ID                           string                                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PoolPubKey                   gitlab_com_thorchain_thornode_common.PubKey `protobuf:"bytes,2,opt,name=pool_pub_key,json=poolPubKey,proto3,casttype=gitlab.com/thorchain/thornode/common.PubKey" json:"pool_pub_key,omitempty"`
	PubKeys                      []string                                    `protobuf:"bytes,3,rep,name=pub_keys,json=pubKeys,proto3" json:"pub_keys,omitempty"`
	BlockHeight                  int64                                       `protobuf:"varint,4,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Chains                       []string                                    `protobuf:"bytes,5,rep,name=chains,proto3" json:"chains,omitempty"`
	Signers                      []string                                    `protobuf:"bytes,6,rep,name=signers,proto3" json:"signers,omitempty"`
	MajorityConsensusBlockHeight int64                                       `protobuf:"varint,7,opt,name=majority_consensus_block_height,json=majorityConsensusBlockHeight,proto3" json:"majority_consensus_block_height,omitempty"`
	Secp256K1Signatures          []string                                    `protobuf:"bytes,8,rep,name=secp256k1_signatures,json=secp256k1Signatures,proto3" json:"secp256k1_signatures,omitempty"`
}

func (m *TssVoter) Reset()      { *m = TssVoter{} }
func (*TssVoter) ProtoMessage() {}
func (*TssVoter) Descriptor() ([]byte, []int) {
	return fileDescriptor_20a5d6b0c0644fdf, []int{0}
}
func (m *TssVoter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TssVoter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TssVoter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TssVoter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TssVoter.Merge(m, src)
}
func (m *TssVoter) XXX_Size() int {
	return m.Size()
}
func (m *TssVoter) XXX_DiscardUnknown() {
	xxx_messageInfo_TssVoter.DiscardUnknown(m)
}

var xxx_messageInfo_TssVoter proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TssVoter)(nil), "types.TssVoter")
}

func init() { proto.RegisterFile("types/type_tss.proto", fileDescriptor_20a5d6b0c0644fdf) }

var fileDescriptor_20a5d6b0c0644fdf = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0xcd, 0x4e, 0xc2, 0x40,
	0x18, 0x6c, 0x8b, 0x14, 0x58, 0x39, 0xad, 0x84, 0xac, 0xc6, 0x2c, 0xe8, 0x89, 0xc4, 0x84, 0x06,
	0x8d, 0x3e, 0x00, 0x6a, 0xa2, 0xf1, 0xa2, 0xf5, 0xe7, 0xe0, 0xa5, 0x69, 0xcb, 0xa6, 0xad, 0xd0,
	0x6e, 0xd3, 0x6f, 0x9b, 0xd8, 0x9b, 0x8f, 0xe0, 0x63, 0x71, 0xe4, 0xc8, 0x09, 0xa5, 0xbc, 0x85,
	0x27, 0xd3, 0xe5, 0x27, 0x78, 0xf1, 0xb2, 0x99, 0x6f, 0x66, 0x76, 0x26, 0xf9, 0x3e, 0xd4, 0x10,
	0x59, 0xcc, 0xc0, 0x28, 0x5e, 0x4b, 0x00, 0x74, 0xe3, 0x84, 0x0b, 0x8e, 0xcb, 0x92, 0x3d, 0x68,
	0x78, 0xdc, 0xe3, 0x92, 0x31, 0x0a, 0xb4, 0x14, 0x8f, 0xbf, 0x34, 0x54, 0x7d, 0x02, 0x78, 0xe1,
	0x82, 0x25, 0xb8, 0x89, 0xb4, 0x60, 0x40, 0xd4, 0xb6, 0xda, 0xa9, 0xf5, 0xf5, 0x7c, 0xd6, 0xd2,
	0x6e, 0xaf, 0x4c, 0x2d, 0x18, 0xe0, 0x07, 0x54, 0x8f, 0x39, 0x1f, 0x59, 0x71, 0xea, 0x58, 0x43,
	0x96, 0x11, 0x4d, 0x3a, 0x8c, 0x9f, 0x59, 0xeb, 0xc4, 0x0b, 0xc4, 0xc8, 0x76, 0xba, 0x2e, 0x0f,
	0x0d, 0xe1, 0xf3, 0xc4, 0xf5, 0xed, 0x20, 0x92, 0x28, 0xe2, 0x03, 0x66, 0xb8, 0x3c, 0x0c, 0x79,
	0xd4, 0xbd, 0x4f, 0x9d, 0x3b, 0x96, 0x99, 0xa8, 0x08, 0x59, 0x62, 0xbc, 0x8f, 0xaa, 0xab, 0x34,
	0x20, 0xa5, 0x76, 0xa9, 0x53, 0x33, 0x2b, 0xb1, 0x54, 0x00, 0x1f, 0xa1, 0xba, 0x33, 0xe2, 0xee,
	0xd0, 0xf2, 0x59, 0xe0, 0xf9, 0x82, 0xec, 0xb4, 0xd5, 0x4e, 0xc9, 0xdc, 0x95, 0xdc, 0x8d, 0xa4,
	0x70, 0x13, 0xe9, 0xb2, 0x09, 0x48, 0x59, 0xfe, 0x5d, 0x4d, 0x98, 0xa0, 0x0a, 0x04, 0x5e, 0xc4,
	0x12, 0x20, 0xfa, 0x32, 0x74, 0x35, 0xe2, 0x6b, 0xd4, 0x0a, 0xed, 0x37, 0x9e, 0x04, 0x22, 0xb3,
	0x5c, 0x1e, 0x01, 0x8b, 0x20, 0x05, 0xeb, 0x4f, 0x4f, 0x45, 0xf6, 0x1c, 0xae, 0x6d, 0x97, 0x6b,
	0x57, 0x7f, 0xab, 0xb8, 0x87, 0x1a, 0xc0, 0xdc, 0xf8, 0xf4, 0xfc, 0x62, 0xd8, 0xb3, 0x8a, 0x6c,
	0x5b, 0xa4, 0x09, 0x03, 0x52, 0x95, 0x6d, 0x7b, 0x1b, 0xed, 0x71, 0x23, 0xf5, 0x9f, 0xc7, 0x73,
	0xaa, 0x4c, 0xe7, 0x54, 0xf9, 0xc8, 0xa9, 0x32, 0xce, 0xa9, 0x3a, 0xc9, 0xa9, 0xfa, 0x9d, 0x53,
	0xf5, 0x73, 0x41, 0x95, 0xc9, 0x82, 0x2a, 0xd3, 0x05, 0x55, 0x5e, 0x8d, 0xff, 0x17, 0xf9, 0xbe,
	0x4d, 0x16, 0xe7, 0x74, 0x74, 0x79, 0xbf, 0xb3, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x45, 0x67,
	0xe6, 0xe3, 0xf4, 0x01, 0x00, 0x00,
}

func (m *TssVoter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TssVoter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TssVoter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Secp256K1Signatures) > 0 {
		for iNdEx := len(m.Secp256K1Signatures) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Secp256K1Signatures[iNdEx])
			copy(dAtA[i:], m.Secp256K1Signatures[iNdEx])
			i = encodeVarintTypeTss(dAtA, i, uint64(len(m.Secp256K1Signatures[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	if m.MajorityConsensusBlockHeight != 0 {
		i = encodeVarintTypeTss(dAtA, i, uint64(m.MajorityConsensusBlockHeight))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Signers) > 0 {
		for iNdEx := len(m.Signers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Signers[iNdEx])
			copy(dAtA[i:], m.Signers[iNdEx])
			i = encodeVarintTypeTss(dAtA, i, uint64(len(m.Signers[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Chains) > 0 {
		for iNdEx := len(m.Chains) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Chains[iNdEx])
			copy(dAtA[i:], m.Chains[iNdEx])
			i = encodeVarintTypeTss(dAtA, i, uint64(len(m.Chains[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.BlockHeight != 0 {
		i = encodeVarintTypeTss(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.PubKeys) > 0 {
		for iNdEx := len(m.PubKeys) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.PubKeys[iNdEx])
			copy(dAtA[i:], m.PubKeys[iNdEx])
			i = encodeVarintTypeTss(dAtA, i, uint64(len(m.PubKeys[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.PoolPubKey) > 0 {
		i -= len(m.PoolPubKey)
		copy(dAtA[i:], m.PoolPubKey)
		i = encodeVarintTypeTss(dAtA, i, uint64(len(m.PoolPubKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintTypeTss(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypeTss(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypeTss(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TssVoter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovTypeTss(uint64(l))
	}
	l = len(m.PoolPubKey)
	if l > 0 {
		n += 1 + l + sovTypeTss(uint64(l))
	}
	if len(m.PubKeys) > 0 {
		for _, s := range m.PubKeys {
			l = len(s)
			n += 1 + l + sovTypeTss(uint64(l))
		}
	}
	if m.BlockHeight != 0 {
		n += 1 + sovTypeTss(uint64(m.BlockHeight))
	}
	if len(m.Chains) > 0 {
		for _, s := range m.Chains {
			l = len(s)
			n += 1 + l + sovTypeTss(uint64(l))
		}
	}
	if len(m.Signers) > 0 {
		for _, s := range m.Signers {
			l = len(s)
			n += 1 + l + sovTypeTss(uint64(l))
		}
	}
	if m.MajorityConsensusBlockHeight != 0 {
		n += 1 + sovTypeTss(uint64(m.MajorityConsensusBlockHeight))
	}
	if len(m.Secp256K1Signatures) > 0 {
		for _, s := range m.Secp256K1Signatures {
			l = len(s)
			n += 1 + l + sovTypeTss(uint64(l))
		}
	}
	return n
}

func sovTypeTss(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypeTss(x uint64) (n int) {
	return sovTypeTss(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TssVoter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypeTss
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TssVoter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TssVoter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTss
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeTss
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTss
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolPubKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTss
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeTss
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTss
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolPubKey = gitlab_com_thorchain_thornode_common.PubKey(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKeys", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTss
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeTss
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTss
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubKeys = append(m.PubKeys, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTss
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chains", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTss
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeTss
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTss
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chains = append(m.Chains, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTss
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeTss
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTss
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signers = append(m.Signers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MajorityConsensusBlockHeight", wireType)
			}
			m.MajorityConsensusBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTss
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MajorityConsensusBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Secp256K1Signatures", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTss
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeTss
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTss
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Secp256K1Signatures = append(m.Secp256K1Signatures, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypeTss(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypeTss
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypeTss(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypeTss
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeTss
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeTss
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypeTss
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypeTss
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypeTss
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypeTss        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypeTss          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypeTss = fmt.Errorf("proto: unexpected end of group")
)
