linters:
  enable:
    - errcheck
    - exportloopref
    - forcetypeassert
    - gocritic
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - promlinter
    - staticcheck
    - typecheck
    - unconvert
    - unused
linters-settings:
  exhaustive:
    check-generated: false
  staticcheck:
    checks: ["all"]
  revive:
    rules:
      - name: exported
        disabled: true
  govet:
    enable:
      - shadow
    settings:
      shadow:
        strict: true
  gosec:
    excludes:
      - G107 # variable urls
      # TODO: re-enable this after fixing all instances.
      - G115 # integer overflow
issues:
  exclude-rules:
    - linters:
        - govet
      text: 'declaration of "err" shadows declaration'
